.gitignore, tests/test_example/square_tests.py
This PR is about adding example of test cases in this repo.
=> Add example tests

src/model/experiments/lion_experiment/README.md, src/model/experiments/lion_experiment/run.py, src/model/openthaigpt_pretraining_model/optimizer/lion/constants.py, src/model/openthaigpt_pretraining_model/optimizer/lion/utils.py
Changes:
- feat: add an option to use activation checkpointing when running experiment (It helps A LOT when training large model)
- feat: add an option to select `dtype` (float32, bfloat16, float16) when running experiment
- docs: add memory experiment result [here](https://github.com/OpenThaiGPT/openthaigpt-pretraining/tree/new/experiment-optimizer-checkpoint/src/model/experiments/lion_experiment).
Follow up #63
=> experiment(optimizer): update Lion experiment result

src/model/openthaigpt_pretraining_model/spm_trainer.py, tests/model/spm_trainer_test.py
Fix Flake 8 Error
- fix: edit file to match with flake8 error
Fix #67
=> fix(model): resolve flake8 error

src/model/openthaigpt_pretraining_model/models/nanoGPT/model.py, src/model/openthaigpt_pretraining_model/optimizers/lion/utils.py, src/model/scripts/experiments/lion_experiment/README.md
add multi gpu with DistributedDataParallel in [NanoGPT Lion Experiment](https://github.com/OpenThaiGPT/openthaigpt-pretraining/blob/main/src/model/scripts/experiments/lion_experiment/run.py) by follow the example from [NanoGPT](https://github.com/karpathy/nanoGPT/blob/master/train.py)
- test run with default argument
`torchrun --standalone --nproc_per_node=num_gpus src/model/scripts/experiments/lion_experiment/run.py`
- test run with custom argument
`torchrun --standalone --nproc_per_node=num_gpus src/model/scripts/experiments/lion_experiment/run.py --argument`
=> feat(model): Convert NanoGPT Lion Experiment to Multi GPU

.devcontainer/devcontainer.json, README.md, docker/Dockerfile
Setup Docker for model training
- docs: add readme for docker setup
- add Dockerfile and dev container for VS Code
=> build(model): add docker env

src/model/openthaigpt_pretraining_model/optimizers/lion/utils.py, src/model/pyproject.toml
Efficient Optimizer can help a lot when training large model
- add choice `adam8bit` for an optimizer
Close #120
=> feat(model): add adam8bit optim

.github/workflows/build_docker.yaml
This PR is about add auto build docker container workflow and push to `openthaigpt/openthaigpt-pretraining` in docker hub.
- Add `build_docker.yaml` in the workflows.
Close #
=> Add build docker workflow

src/model/openthaigpt_pretraining_model/lightning/utils.py, src/model/pyproject.toml, src/model/scripts/lighting_training/train.py
for logging loss and system on fabric training pipeline
- add wandb offline mode
- change progress bar to enable only main global rank
Close #122
=> feat(model): WanDB with fabric

src/model/openthaigpt_pretraining_model/GPTJ_TH_tokenizer/__init__ .py, src/model/openthaigpt_pretraining_model/data_wrapper.py, src/model/openthaigpt_pretraining_model/datasets/__init__.py, src/model/openthaigpt_pretraining_model/datasets/constants.py, src/model/openthaigpt_pretraining_model/lightning/constants.py, src/model/openthaigpt_pretraining_model/lightning/utils.py, src/model/openthaigpt_pretraining_model/models/gptj/gptj_model_xformers.py, src/model/openthaigpt_pretraining_model/optimizers/__init__.py, src/model/openthaigpt_pretraining_model/optimizers/constants.py, src/model/openthaigpt_pretraining_model/optimizers/lion/constants.py, src/model/openthaigpt_pretraining_model/optimizers/lion/utils.py, src/model/openthaigpt_pretraining_model/utils.py, src/model/scripts/experiments/lion_experiment/run.py, src/model/scripts/lighting_training/train.py
This PR is about refactor model repo in OpenThaiGPT
- Just refactor repo no logical change.
Close #
=> refactor(model): Refactor model repo

src/model/openthaigpt_pretraining_model/trainer/lightning_trainer.py
This PR is about add universal trainer. User can use `train_dataset`, `val_dataset`, `tokenizer`, and `model` as input and can make code trainable.
- Add `LightningTrainer`
Close #
=> feat(model): Add universal trainer

src/model/configuration_example/example_config.yaml, src/model/configuration_example/optimizer/adam1bit_optimizer.yaml, src/model/configuration_example/optimizer/adam8bit_optimizer.yaml, src/model/configuration_example/optimizer/adamw_optimizer.yaml, src/model/configuration_example/optimizer/lion_optimizer.yaml, src/model/openthaigpt_pretraining_model/lightning/utils.py, src/model/openthaigpt_pretraining_model/optimizers/__init__.py, src/model/openthaigpt_pretraining_model/trainer/lightning_trainer.py, src/model/openthaigpt_pretraining_model/utils.py, src/model/pyproject.toml, src/model/scripts/experiments/example_config.yaml, src/model/scripts/experiments/lion_experiment/lion_optimizer_experiment.yml, src/model/scripts/experiments/lion_experiment/optimizer/adamw_optimizer.yaml, src/model/scripts/experiments/lion_experiment/optimizer/lion_optimizer.yaml, src/model/scripts/experiments/lion_experiment/run.py
This PR I tried to setup training optimizers by using hydra yaml (We will do this with `dataset`, `model`, and etc. in the next PR).
- Change all of optimizer hyps to yaml file.
- `CustomOptimizer` in `src/model/openthaigpt_pretraining_model/lightning/utils.py` is for make the current branch to trainable. We will delete it after using Trainer from `src/model/openthaigpt_pretraining_model/trainer/lightning_trainer.py`.
Close #
=> feat(model): Add hydra config

src/model/configuration_example/example_config.yaml, src/model/configuration_example/model/falcon-7b-from-pretrained.yaml, src/model/configuration_example/model/falcon-7b-from-scratch.yaml, src/model/configuration_example/optimizer/adam1bit_optimizer.yaml, src/model/configuration_example/optimizer/adam8bit_optimizer.yaml, src/model/configuration_example/optimizer/adamw_optimizer.yaml, src/model/configuration_example/optimizer/lion_optimizer.yaml, src/model/openthaigpt_pretraining_model/lightning/utils.py, src/model/openthaigpt_pretraining_model/models/__init__.py, src/model/openthaigpt_pretraining_model/models/constants.py, src/model/openthaigpt_pretraining_model/optimizers/__init__.py, src/model/openthaigpt_pretraining_model/trainer/lightning_trainer.py, src/model/openthaigpt_pretraining_model/utils.py, src/model/pyproject.toml, src/model/scripts/experiments/example_config.yaml, src/model/scripts/experiments/lion_experiment/lion_optimizer_experiment.yml, src/model/scripts/experiments/lion_experiment/optimizer/adamw_optimizer.yaml, src/model/scripts/experiments/lion_experiment/optimizer/lion_optimizer.yaml, src/model/scripts/experiments/lion_experiment/run.py
This PR is about adding auto download model feature from hydra yaml config.
- Add falcon model example config.
Close #
=> feat(model): Add model hydra yaml

src/model/scripts/spm_training/README.md, src/model/scripts/spm_training/train.py
add script to train spm_tokenizer for run in lanta
- add script to train spm_tokenizer
Close #
=> refactor(model): add script to train spm_tokenizer

src/model/scripts/lighting_training/load_model.py
use load hf model to local path
- make pipeline to load hf model to local path
Close #
=> feat(model): load hf model to local path

src/model/openthaigpt_pretraining_model/tokenizers/spm_trainer.py, src/model/scripts/bpe_training/train.py
spm train and bpe train use same load dataset function then refactor make function to  use in 2 train pipeline
- make function to load dataset from local path
Close #
=> refactor(model): make load dataset function

src/model/configuration_example/config.yaml, src/model/configuration_example/datasets/mc4.yaml, src/model/configuration_example/datasets/oscar.yaml, src/model/configuration_example/example_config.yaml, src/model/configuration_example/model/falcon-7b-from-pretrained.yaml, src/model/configuration_example/model/falcon-7b-from-scratch.yaml, src/model/configuration_example/model/gptj-6b-from-pretrained.yaml, src/model/configuration_example/model/gptj-6b-from-scratch.yaml, src/model/configuration_example/model/llama-7b-from-pretrained.yaml, src/model/configuration_example/model/llama-7b-from-scratch.yaml, src/model/configuration_example/model/llama-from-scratch.yaml, src/model/openthaigpt_pretraining_model/data_wrapper.py, src/model/openthaigpt_pretraining_model/datasets/__init__.py, src/model/openthaigpt_pretraining_model/lightning/utils.py, src/model/openthaigpt_pretraining_model/models/falcon/model.py, src/model/scripts/experiments/lion_experiment/run.py, src/model/scripts/lighting_training/data_preprocessing.py, src/model/scripts/lighting_training/train.py
refactor get_dataset to use config instead args
- get_dataset to use config instead args
- make yaml file for dataset
Close #
=> refactor(model): get dataset

src/model/openthaigpt_pretraining_model/data_wrapper.py, src/model/openthaigpt_pretraining_model/models/falcon/model.py
make tokenized dataset efficent for train
- update ```tokenize_function``` in ```TokenizedDataset```
Close #
=> feat(model): efficent tokenize

src/model/scripts/lighting_training/tokenizer_info.py
We want tokenizer information to add in ```.yaml``` file
- add pipeline to get infomation about vocab size, eos tag, unk tag from tokenizer
Close #
=> feat(model): get tokenizer infomation pipeline

src/data/scripts/merge_jsonl/merge.sh, src/data/scripts/merge_jsonl/merge_jsonl.py
=> feat(data): add merge jsonl code for oscar dataset

src/data/openthaigpt_pretraining_data/deduplication/deduplication.py, src/data/scripts/deduplication/config/deduplication.yaml
=> perf(data): revamp deduplication parallelism pipeline

src/data/openthaigpt_pretraining_data/blind_pdpa/__init__.py, src/data/scripts/blind_pdpa/blind.py, src/data/scripts/blind_pdpa/config/blind_pdpa.yaml, src/data/scripts/blind_pdpa/submit.sh
=> feat(data): add PDPA blind data script

.github/workflows/test_core.yaml, .github/workflows/test_data.yaml, .github/workflows/test_evaluation.yaml, .github/workflows/test_model.yaml
=> fix(all): github action test failed

.github/workflows/test_core.yaml, .github/workflows/test_data.yaml, .github/workflows/test_evaluation.yaml, .github/workflows/test_model.yaml
=> build(model): add cache in pip github action

src/model/openthaigpt_pretraining_model/lightning/utils.py
=> debug (model): solve unrunnable of lora config

src/model/scripts/sh_file/lighting_training/README.md, src/model/scripts/sh_file/lighting_training/dataprocess.sh, src/model/scripts/sh_file/lighting_training/train.sh
add .sh file for use in lanta
- add .sh of lighting training file for use in lanta
- add README.md for use .sh file of lighting training
Close #
=> feat(model): add sh for lighting training

src/model/configuration_example/data_process/data_process_v1.yaml, src/model/scripts/lighting_training/data_preprocessing.py
Make dataprocess in lighting training can preprocess multi split
- make dataprocess in lighting training can preprocess multi split
Close #
=> refactor(model): Preprocess data multi split

src/model/openthaigpt_pretraining_model/lightning/utils.py
=> debug (model): solve unrunnable from lora config

src/model/openthaigpt_pretraining_model/lightning/utils.py
Deepspeed have bug when save and load
- fix bug save and load of deepspeed
Close #
=> debug(model): fix save and load deepspeed

src/model/openthaigpt_pretraining_model/lightning/utils.py
Update learning rate by ```global_step```
- Update learning rate by ```global_step```
Close #
=> fix(model): Use global step to update learning rate

src/model/configuration_example/lora/README.md, src/model/configuration_example/lora/falcon.yaml, src/model/openthaigpt_pretraining_model/models/__init__.py, src/model/openthaigpt_pretraining_model/models/constants.py
prepare for train falcon-7B
- add lora config for Falcon
- test with bf16 and deepspeed 2
- [] PR should be in the [Naming convention](../../docs/PR_NAMING.md)
=> feat(model): add lora config for falcon

src/model/openthaigpt_pretraining_model/tokenizers/spm_trainer.py, src/model/scripts/llama_thai_tokenizer/merge_tokenizer.py
Change bos eos and unk of spm trainer to default
- Change bos eos and unk of spm trainer
- Add make dir before train spm
Close #
=> Fix(model): Update token for spm trainer

src/model/configuration_example/training/README.md, src/model/configuration_example/training/training_v1.yaml, src/model/openthaigpt_pretraining_model/lightning/utils.py
Add gradient clipping for deepspeed
- Add gradient clipping in deepspeed config
Close #
=> feat(model): Add gradient clipping

src/model/openthaigpt_pretraining_model/lightning/utils.py
Fix eval step
- Fix eval step
Close #
=> fix(model): Fix eval step

src/data/scripts/deduplication/README.md
To have documentation on deduplication code
- Add readme for deduplication script
=> docs(data): add info on deduplication

src/model/configuration_example/spm/README.md, src/model/configuration_example/spm/training_v1.yaml, src/model/openthaigpt_pretraining_model/tokenizers/spm_trainer.py, src/model/scripts/llama_thai_tokenizer/README.md, src/model/scripts/spm_training/README.md
=> docs: Document Tokenizer training Pipeline

src/model/scripts/lighting_training/data_preprocessing.py
This PR is about using `num_proc` arguments on `save_to_disk` function to speed up saving dataset.
- Add `num_proc` arguments on `save_to_disk` function
Close #
=> Speed up data preprocessing save_to_disk

src/data/scripts/pile/convert_the_pile.py
make pipeline for convert pile dataset to hf dataset with our format
- add pipeline for pile dataset to hf dataset
Close #
=> feat(data): Convert the Pile dataset to hf format

src/data/scripts/internet/main.py
Add function create oscar colassal dataset to openthaigpt-pretraining\src\data\scripts\internet\main.py
Close #
=> Add function to create oscar colassal dataset

src/model/scripts/hf_trainer/README.md, src/model/scripts/hf_trainer/sbatch submit_deepspeed.sh, src/model/scripts/hf_trainer/smultinode_deepspeed.sh, src/model/scripts/hf_trainer/train.py
merge dataset in hf dataset by can set weight of dataset
- hf trainer pipeline can merge dataset
Close #
=> feat(model): Combined dataset to HF pipeline

src/core/pyproject.toml, src/data/openthaigpt_pretraining_data/decontamination/utils.py, src/data/pyproject.toml, src/data/scripts/decontamination/config/datasets/ted_talks_iwslt_th_en.yaml, src/data/scripts/decontamination/config/decontamination.yaml, src/data/scripts/deduplication/config/deduplication.yaml, src/data/scripts/deduplication/submit.sh
=> edit pyproject / config dedup&decont

src/data/scripts/crawl_thaigov/README.md, src/data/scripts/crawl_thaigov/nuch_crawl_thaigov_all.py, src/model/notebook/QLoRA_vs_LoRA Report(Training time + tflops)/lora.dvc
=> feat(model): update thaigov pipeline to align with the updated website [LM-198]

src/data/openthaigpt_pretraining_data/internet/cleaning/cleaning.py, src/data/openthaigpt_pretraining_data/internet/cleaning/constants.py, src/data/scripts/internet/main.py
Clean data from internet by 
- filter short text
- filter cookies
- dedup 3 line
- clean no meaningful data
- filter short text
- filter cookies
- dedup 3 line
- clean no meaningful data
Close #
=> Internet Cleaning [LM-225]

onet/main.py
- This is a code to clean onet which is in microsoft word file into json. It will be easier to use for traning.
- Code to read word file text
- Convert all equation to readable LaTeX format (follow LLMU format)
- Save to json format as the following example
- Implement ignore case where we don't want to include these type of question, for example
- question with image   
Waiting for more test case from other onet subject
https://github.com/OpenThaiGPT/openthaigpt-pretraining/issues/64
=> Onet test data
